spring.application.name=tienda-k

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda-k
spring.datasource.username=13rian
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

